Extend the detection of connection lost in the PostgreSQL ExceptionConverter (#7010)
|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | 

#### Summary

In some cases I'm getting the following exception:
`Doctrine\DBAL\Exception\DriverException #7
An exception occurred while executing a query: SQLSTATE[HY000]: General
error: 7 server closed the connection unexpectedly
This probably means the server terminated abnormally before or while
processing the request. `

I think this exception should be converted to the ConnectionLost
exception.